spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
    devtools:
      livereload:
        enabled: true
      restart:
        enabled: ture
      thymeleaf:
        cache: false

  jwt:
    header: Authorization
    #secret : 별도 문자열을 base64로 암호화한값
    secret: c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK
    #토큰만료시간(ms)
    token-validity-in-seconds: 3600